// Auto-generated from the canonical Legenex registry exports
// (custom-fields-2026-09-07.json / calculated-fields-2026-09-07.json).
// Loaded by the "Load default registry" action on the Custom Fields and
// Calculated Fields pages. Import is idempotent: existing names/tokens are
// skipped, so re-running never duplicates or overwrites live config.

export const CUSTOM_FIELDS_SEED = [
  {
    "field_name": "timestamp",
    "label": "Timestamp",
    "field_type": "system",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "timestamp",
    "auto_created": false,
    "sort_order": 0,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "lead_route",
    "label": "Lead Route",
    "field_type": "system",
    "source": "inbound",
    "sample_value": "standard",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "lead_route",
    "auto_created": true,
    "sort_order": 1,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "lead_status",
    "label": "Lead Status",
    "field_type": "system",
    "source": "inbound",
    "sample_value": "",
    "options": [
      "Qualified",
      "Disqualified",
      "Sold",
      "Unsold",
      "Rejected",
      "Duplicates",
      "Queued"
    ],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "lead_status",
    "auto_created": false,
    "sort_order": 2,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "lead_type",
    "label": "Lead Type",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [
      "Quiz",
      "Advertorial",
      "Lander",
      "Inbound Call",
      "Partner Data",
      "Affiliate",
      "Lead Form",
      "Email",
      "ChatBot"
    ],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "lead_type",
    "auto_created": false,
    "sort_order": 3,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "vertical",
    "label": "Vertical",
    "field_type": "system",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "vertical",
    "auto_created": false,
    "sort_order": 3,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "supplier_type",
    "label": "Supplier Type",
    "field_type": "system",
    "source": "inbound",
    "sample_value": "",
    "options": [
      "Internal",
      "External",
      "Calls"
    ],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "supplier_type",
    "auto_created": false,
    "sort_order": 3.5,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "lead_id",
    "label": "Lead Id",
    "field_type": "system",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "lead_id",
    "auto_created": false,
    "sort_order": 4,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "sid",
    "label": "Supplier ID",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "sid",
    "auto_created": false,
    "sort_order": 5,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "campid",
    "label": "Campid",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "campid",
    "auto_created": false,
    "sort_order": 5,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "ssid",
    "label": "Supplier SubID",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "ssid",
    "auto_created": false,
    "sort_order": 6,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "email_valid",
    "label": "Email Valid",
    "field_type": "system",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "email_valid",
    "auto_created": false,
    "sort_order": 6,
    "required": false,
    "system_role": "email_valid"
  },
  {
    "field_name": "s1",
    "label": "S1",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "c1",
    "auto_created": false,
    "sort_order": 7,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "s2",
    "label": "S2",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "c2",
    "auto_created": false,
    "sort_order": 8,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "supplier_brand",
    "label": "Supplier Brand",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "supplier_brand",
    "auto_created": false,
    "sort_order": 10,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "optin_url",
    "label": "Optin Url",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "optinurl",
    "auto_created": false,
    "sort_order": 11,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "trustedform_url",
    "label": "Trustedform Url",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "trustedform_url",
    "auto_created": false,
    "sort_order": 12,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "ip_address",
    "label": "IP Address",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "ip_address",
    "auto_created": false,
    "sort_order": 13,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "first_name",
    "label": "First Name",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "firstname",
    "auto_created": false,
    "sort_order": 14,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "last_name",
    "label": "Last Name",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "lastname",
    "auto_created": false,
    "sort_order": 15,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "mobile",
    "label": "Mobile",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "phone1",
    "auto_created": false,
    "sort_order": 16,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "email",
    "label": "Email",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "email",
    "auto_created": false,
    "sort_order": 17,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "zip",
    "label": "Zip",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "zip",
    "auto_created": false,
    "sort_order": 18,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "accident_type",
    "label": "Accident Type",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "accident_type",
    "auto_created": false,
    "sort_order": 19,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "accident_state",
    "label": "Accident State",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "accident_state",
    "auto_created": false,
    "sort_order": 20,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "incident_date",
    "label": "Incident Date",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "incident_date",
    "auto_created": false,
    "sort_order": 21,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "accident_date",
    "label": "Accident Date",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "accident_date",
    "auto_created": false,
    "sort_order": 22,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "accident_details",
    "label": "Accident Details",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "accident_details",
    "auto_created": false,
    "sort_order": 23,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "injured",
    "label": "Injured",
    "field_type": "dropdown",
    "source": "inbound",
    "sample_value": "",
    "options": [
      "Yes",
      "No"
    ],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "injured",
    "auto_created": false,
    "sort_order": 24,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "injury_type",
    "label": "Injury Type",
    "field_type": "dropdown",
    "source": "inbound",
    "sample_value": "",
    "options": [
      "Loss Of Life",
      "Brain Injury",
      "Back Or Neck Pain",
      "Broken Bones",
      "Cuts and Bruises",
      "No Injury"
    ],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "injury_type",
    "auto_created": false,
    "sort_order": 25,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "treatment",
    "label": "Treatment",
    "field_type": "dropdown",
    "source": "inbound",
    "sample_value": "",
    "options": [
      "Yes",
      "No"
    ],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "treatment",
    "auto_created": false,
    "sort_order": 26,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "treatment_type",
    "label": "Treatment Type",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "treatment_type",
    "auto_created": false,
    "sort_order": 27,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "fault",
    "label": "Fault",
    "field_type": "dropdown",
    "source": "inbound",
    "sample_value": "",
    "options": [
      "Yes",
      "No"
    ],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "fault",
    "auto_created": false,
    "sort_order": 29,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "attorney",
    "label": "Attorney",
    "field_type": "dropdown",
    "source": "inbound",
    "sample_value": "",
    "options": [
      "Yes",
      "No"
    ],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "attorney",
    "auto_created": false,
    "sort_order": 30,
    "required": true,
    "system_role": ""
  },
  {
    "field_name": "insurance",
    "label": "Insurance",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "insurance",
    "auto_created": false,
    "sort_order": 31,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "police_report",
    "label": "Police Report",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "police_report",
    "auto_created": false,
    "sort_order": 32,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "utm_source",
    "label": "UTM Source",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "utm_source",
    "auto_created": false,
    "sort_order": 33,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "utm_campaign",
    "label": "UTM Campaign",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "utm_campaign",
    "auto_created": false,
    "sort_order": 34,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "utm_medium",
    "label": "UTM Medium",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "utm_medium",
    "auto_created": false,
    "sort_order": 35,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "utm_content",
    "label": "UTM Content",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "utm_content",
    "auto_created": false,
    "sort_order": 36,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "utm_terms",
    "label": "UTM Terms",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "utm_terms",
    "auto_created": false,
    "sort_order": 37,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "ad_label",
    "label": "Ad Label",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "utm_ad_label",
    "auto_created": false,
    "sort_order": 38,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "geoip_country",
    "label": "GeoIP Country",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "country",
    "auto_created": false,
    "sort_order": 39,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "geoip_zip",
    "label": "GeoIP Zip",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "geo_zip",
    "auto_created": false,
    "sort_order": 40,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "geoip_state",
    "label": "GeoIP State",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "geo_state",
    "auto_created": false,
    "sort_order": 41,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "geoip_city",
    "label": "GeoIP City",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "geo_city",
    "auto_created": false,
    "sort_order": 42,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "fbp",
    "label": "Fbp",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "fbp",
    "auto_created": false,
    "sort_order": 43,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "fbc",
    "label": "Fbc",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "fbc",
    "auto_created": false,
    "sort_order": 44,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "event_id",
    "label": "Event Id",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "event_id",
    "auto_created": false,
    "sort_order": 45,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "event_time",
    "label": "Event Time",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "event_time",
    "auto_created": false,
    "sort_order": 46,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "tc_id",
    "label": "Tc Id",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "tc_id",
    "auto_created": false,
    "sort_order": 47,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "timezone",
    "label": "Timezone",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "timezone",
    "auto_created": false,
    "sort_order": 48,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "cf_transaction_id",
    "label": "Cf Transaction Id",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "cf_transaction_id",
    "auto_created": false,
    "sort_order": 49,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "jornaya_token",
    "label": "Jornaya Token",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "jornaya_token",
    "auto_created": false,
    "sort_order": 50,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "revenue",
    "label": "Revenue",
    "field_type": "number",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "revenue",
    "auto_created": false,
    "sort_order": 51,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "conv_value",
    "label": "Conv Value",
    "field_type": "number",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "conv_value",
    "auto_created": false,
    "sort_order": 52,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "phone_verified",
    "label": "Phone Verified",
    "field_type": "system",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "phone_verified",
    "auto_created": false,
    "sort_order": 53,
    "required": false,
    "system_role": "phone_verified"
  },
  {
    "field_name": "accident_date_2",
    "label": "Accident Date 2",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "accident_date_2",
    "auto_created": false,
    "sort_order": 54,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "accident_date_3",
    "label": "Accident Date 3",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "accident_date_3",
    "auto_created": false,
    "sort_order": 55,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "incident_date_2",
    "label": "Incident Date 2",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "incident_date_2",
    "auto_created": false,
    "sort_order": 56,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "incident_date_3",
    "label": "Incident Date 3",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "incident_date_3",
    "auto_created": false,
    "sort_order": 57,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "has_attorney",
    "label": "Has Attorney",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "has_attorney",
    "auto_created": false,
    "sort_order": 58,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "cpl",
    "label": "CPL",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "cpl",
    "auto_created": false,
    "sort_order": 65,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "profit",
    "label": "Profit",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "profit",
    "auto_created": false,
    "sort_order": 66,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "net_profit",
    "label": "Net Profit",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "net_profit",
    "auto_created": false,
    "sort_order": 67,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "Supplier Source",
    "label": "Source",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "Facebook",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "source",
    "auto_created": true,
    "sort_order": 68,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "user_agent",
    "label": "User Agent",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "user_agent",
    "auto_created": false,
    "sort_order": 70,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "geo_language",
    "label": "Geo Language",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "geo_language",
    "auto_created": false,
    "sort_order": 71,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "s3",
    "label": "S3",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "c3",
    "auto_created": false,
    "sort_order": 72,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "leadshook_id",
    "label": "LeadShook Id",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "ef_transaction_id",
    "auto_created": false,
    "sort_order": 73,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "supplier_payout",
    "label": "Payout",
    "field_type": "number",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "supplier_payout",
    "auto_created": false,
    "sort_order": 74,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "attorney_change",
    "label": "Attorney Change",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "attorney_change",
    "auto_created": false,
    "sort_order": 74,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "buyer_name",
    "label": "Buyer Name",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "buyer_name",
    "auto_created": false,
    "sort_order": 75,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "accident_timeframe",
    "label": "Accident Timeframe",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "",
    "auto_created": false,
    "sort_order": 75,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "buyer_id",
    "label": "Buyer ID",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "buyer_id",
    "auto_created": false,
    "sort_order": 76,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "buyer_feedback",
    "label": "feedback",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "buyer_feedback",
    "auto_created": false,
    "sort_order": 77,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "returned",
    "label": "Returned",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "returned",
    "auto_created": false,
    "sort_order": 78,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "source",
    "label": "Source",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "Facebook",
    "options": [],
    "include_in_leadbyte": false,
    "leadbyte_field_name": "source",
    "auto_created": true,
    "sort_order": 79,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "return_reason",
    "label": "Returned Reason",
    "field_type": "string",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "returned_reason",
    "auto_created": false,
    "sort_order": 79,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "treatment_time",
    "label": "Treatment Time",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "treatment_time",
    "auto_created": true,
    "sort_order": 80,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "injury_type_2",
    "label": "Injuury Type 2",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "injuury_type_2",
    "auto_created": true,
    "sort_order": 80,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "type_of_injury",
    "label": "Type Of Injury",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "type_of_injury",
    "auto_created": true,
    "sort_order": 81,
    "required": false,
    "system_role": ""
  },
  {
    "field_name": "injury_type_2",
    "label": "Injury Type 2",
    "field_type": "Calculated",
    "source": "inbound",
    "sample_value": "",
    "options": [],
    "include_in_leadbyte": true,
    "leadbyte_field_name": "injury_type_2",
    "auto_created": true,
    "sort_order": 81,
    "required": false,
    "system_role": ""
  }
];

export const CALCULATED_FIELDS_SEED = [
  {
    "transform_type": "value_map",
    "input_field": "injury_type",
    "output_token": "type_of_injury",
    "output_label": "Type Of Injury",
    "vertical": "MVA",
    "config": "{\"map\":{\"Loss Of Life\":\"Catastrophic\",\"Brain Injury\":\"Catastrophic\",\"Back Or Neck Pain\":\"Severe Injury\",\"Broken Bones\":\"Severe Injury\",\"Cuts and Bruises\":\"Soft Tissue\",\"No Injury\":\"None\"}}",
    "sort_order": 0,
    "enabled": true
  },
  {
    "transform_type": "value_map",
    "input_field": "injury_type",
    "output_token": "injury_type_2",
    "output_label": "Injury Type 2",
    "vertical": "MVA",
    "config": "{\"map\":{\"Loss Of Life\":\"Catastrophic\",\"Brain Injury\":\"Catastrophic\",\"Back Or Neck Pain\":\"Severe Injury\",\"Broken Bones\":\"Severe Injury\",\"Cuts and Bruises\":\"Soft Tissue\",\"No Injury\":\"No Injury\"}}",
    "sort_order": 0,
    "enabled": true
  },
  {
    "transform_type": "value_map",
    "input_field": "injury_type",
    "output_token": "treatment_time",
    "output_label": "Treatment Time",
    "vertical": "MVA",
    "config": "{\"map\":{\"Loss Of Life\":\"Within 7 Days\",\"Brain Injury\":\"Within 7 Days\",\"Back Or Neck Pain\":\"Within 14 Days\",\"Broken Bones\":\"Within 7 Days\",\"Cuts and Bruises\":\"Within 14 Days\",\"No Injury\":\"Never\"}}",
    "sort_order": 0,
    "enabled": true
  },
  {
    "transform_type": "value_map",
    "input_field": "injury_type",
    "output_token": "treatment_type",
    "output_label": "Treatment Type",
    "vertical": "MVA",
    "config": "{\"map\":{\"Loss Of Life\":\"Hospital\",\"Brain Injury\":\"Surgery\",\"Back Or Neck Pain\":\"Surgery\",\"Broken Bones\":\"Surgery\",\"Cuts and Bruises\":\"Doctor\",\"No Injury\":\"None\"}}",
    "sort_order": 0,
    "enabled": true
  },
  {
    "transform_type": "clone",
    "input_field": "utm_source",
    "output_token": "Supplier Source",
    "output_label": "Source",
    "vertical": "",
    "config": "{}",
    "sort_order": 0,
    "enabled": true
  },
  {
    "transform_type": "date_age_bucket",
    "input_field": "incident_date",
    "output_token": "accident_date",
    "output_label": "Accident Date Bucket",
    "vertical": "MVA",
    "config": "{\"buckets\":[{\"label\":\"Within 7 Days\",\"max_days\":7},{\"label\":\"Within 14 Days\",\"max_days\":14},{\"label\":\"Within 30 Days\",\"max_days\":30},{\"label\":\"Within 3 Months\",\"max_days\":90},{\"label\":\"Within 6 Months\",\"max_days\":180},{\"label\":\"Within 12 Months\",\"max_days\":365},{\"label\":\"Within 18 Months\",\"max_days\":545},{\"label\":\"Within 24 Months\",\"max_days\":730}],\"fallback\":\"Over 24 Months\",\"date_format\":\"MM/DD/YYYY\"}",
    "sort_order": 0,
    "enabled": true
  },
  {
    "transform_type": "date_age_bucket",
    "input_field": "incident_date",
    "output_token": "incident_date_3",
    "output_label": "Incident Date 3",
    "vertical": "MVA",
    "config": "{\"buckets\":[{\"label\":\"In the last 30 days\",\"max_days\":7},{\"label\":\"In the last 30 days\",\"max_days\":14},{\"label\":\"In the last 30 days\",\"max_days\":30},{\"label\":\"In the last 12 months\",\"max_days\":90},{\"label\":\"In the last 12 months\",\"max_days\":180},{\"label\":\"In the last 12 months\",\"max_days\":365},{\"label\":\"In the last 2 years\",\"max_days\":545},{\"label\":\"In the last 2 years\",\"max_days\":730}],\"fallback\":\"Over 24 Months\",\"date_format\":\"MM/DD/YYYY\"}",
    "sort_order": 1,
    "enabled": true
  },
  {
    "transform_type": "date_age_bucket",
    "input_field": "incident_date",
    "output_token": "accident_date_2",
    "output_label": "accident_date_2",
    "config": "{\"buckets\":[{\"label\":\"30_days\",\"max_days\":7},{\"label\":\"30_days\",\"max_days\":14},{\"label\":\"30_days\",\"max_days\":30},{\"label\":\"3_months\",\"max_days\":90},{\"label\":\"6_months\",\"max_days\":180},{\"label\":\"12_months\",\"max_days\":365},{\"label\":\"2_years\",\"max_days\":545},{\"label\":\"2_years\",\"max_days\":730}],\"fallback\":\"2+_years\",\"date_format\":\"MM/DD/YYYY\"}",
    "sort_order": 2,
    "enabled": true
  },
  {
    "transform_type": "value_map",
    "input_field": "attorney",
    "output_token": "has_attorney",
    "output_label": "Has Attorney",
    "vertical": "MVA",
    "config": "{\"map\":{\"yes\":\"Yes\",\"Yes\":\"Yes\",\"YES\":\"Yes\",\"true\":\"Yes\",\"True\":\"Yes\",\"TRUE\":\"Yes\",\"has attorney\":\"Yes\",\"Has Attorney\":\"Yes\",\"no\":\"No\",\"No\":\"No\",\"NO\":\"No\",\"false\":\"No\",\"False\":\"No\",\"FALSE\":\"No\"}}",
    "sort_order": 3,
    "enabled": true
  },
  {
    "transform_type": "value_map",
    "input_field": "accident_state",
    "output_token": "state_full",
    "output_label": "State Full",
    "config": "{\"map\":{\"AL\":\"AL Alabama\",\"AK\":\"AK Alaska\",\"AZ\":\"AZ Arizona\",\"AR\":\"AR Arkansas\",\"CA\":\"CA California\",\"CO\":\"CO Colorado\",\"CT\":\"CT Connecticut\",\"DE\":\"DE Delaware\",\"FL\":\"FL Florida\",\"GA\":\"GA Georgia\",\"HI\":\"HI Hawaii\",\"ID\":\"ID Idaho\",\"IL\":\"IL Illinois\",\"IN\":\"IN Indiana\",\"IA\":\"IA Iowa\",\"KS\":\"KS Kansas\",\"KY\":\"KY Kentucky\",\"LA\":\"LA Louisiana\",\"ME\":\"ME Maine\",\"MD\":\"MD Maryland\",\"MA\":\"MA Massachusetts\",\"MI\":\"MI Michigan\",\"MN\":\"MN Minnesota\",\"MS\":\"MS Mississippi\",\"MO\":\"MO Missouri\",\"MT\":\"MT Montana\",\"NE\":\"NE Nebraska\",\"NV\":\"NV Nevada\",\"NH\":\"NH New Hampshire\",\"NJ\":\"NJ New Jersey\",\"NM\":\"NM New Mexico\",\"NY\":\"NY New York\",\"NC\":\"NC North Carolina\",\"ND\":\"ND North Dakota\",\"OH\":\"OH Ohio\",\"OK\":\"OK Oklahoma\",\"OR\":\"OR Oregon\",\"PA\":\"PA Pennsylvania\",\"RI\":\"RI Rhode Island\",\"SC\":\"SC South Carolina\",\"SD\":\"SD South Dakota\",\"TN\":\"TN Tennessee\",\"TX\":\"TX Texas\",\"UT\":\"UT Utah\",\"VT\":\"VT Vermont\",\"VA\":\"VA Virginia\",\"WA\":\"WA Washington\",\"WV\":\"WV West Virginia\",\"WI\":\"WI Wisconsin\",\"WY\":\"WY Wyoming\"}}",
    "sort_order": 4,
    "enabled": true
  },
  {
    "transform_type": "value_map",
    "input_field": "accident_state",
    "output_token": "state_name",
    "output_label": "State Name",
    "config": "{\"map\":{\"AL\":\"Alabama\",\"AK\":\"Alaska\",\"AZ\":\"Arizona\",\"AR\":\"Arkansas\",\"CA\":\"California\",\"CO\":\"Colorado\",\"CT\":\"Connecticut\",\"DE\":\"Delaware\",\"FL\":\"Florida\",\"GA\":\"Georgia\",\"HI\":\"Hawaii\",\"ID\":\"Idaho\",\"IL\":\"Illinois\",\"IN\":\"Indiana\",\"IA\":\"Iowa\",\"KS\":\"Kansas\",\"KY\":\"Kentucky\",\"LA\":\"Louisiana\",\"ME\":\"Maine\",\"MD\":\"Maryland\",\"MA\":\"Massachusetts\",\"MI\":\"Michigan\",\"MN\":\"Minnesota\",\"MS\":\"Mississippi\",\"MO\":\"Missouri\",\"MT\":\"Montana\",\"NE\":\"Nebraska\",\"NV\":\"Nevada\",\"NH\":\"New Hampshire\",\"NJ\":\"New Jersey\",\"NM\":\"New Mexico\",\"NY\":\"New York\",\"NC\":\"North Carolina\",\"ND\":\"North Dakota\",\"OH\":\"Ohio\",\"OK\":\"Oklahoma\",\"OR\":\"Oregon\",\"PA\":\"Pennsylvania\",\"RI\":\"Rhode Island\",\"SC\":\"South Carolina\",\"SD\":\"South Dakota\",\"TN\":\"Tennessee\",\"TX\":\"Texas\",\"UT\":\"Utah\",\"VT\":\"Vermont\",\"VA\":\"Virginia\",\"WA\":\"Washington\",\"WV\":\"West Virginia\",\"WI\":\"Wisconsin\",\"WY\":\"Wyoming\"}}",
    "sort_order": 5,
    "enabled": true
  },
  {
    "transform_type": "script",
    "input_field": "incident_date",
    "output_token": "incident_date_2",
    "output_label": "Incident Date 2",
    "config": "{\"script\":\"if (!value) return value;\\nvar m = String(value).match(/(\\\\d{2})\\\\/(\\\\d{2})\\\\/(\\\\d{4})/);\\nif (!m) return value;\\nreturn m[3] + '-' + m[1] + '-' + m[2];\"}",
    "sort_order": 6,
    "enabled": true
  },
  {
    "transform_type": "date_age_bucket",
    "input_field": "incident_date",
    "output_token": "accident_date_3",
    "output_label": "Accident Date 3",
    "config": "{\"buckets\":[{\"label\":\"In the last 30 days\",\"max_days\":30},{\"label\":\"In the last 12 months\",\"max_days\":365},{\"label\":\"In the last 2 years\",\"max_days\":730}],\"fallback\":\"Over 2 years\",\"date_format\":\"MM/DD/YYYY\"}",
    "sort_order": 7,
    "enabled": true
  },
  {
    "transform_type": "conditional",
    "input_field": "",
    "output_token": "lead_type",
    "output_label": "Lead Type",
    "vertical": "",
    "config": "{\"rules\":[{\"conditions\":{\"type\":\"group\",\"match\":\"any\",\"name\":\"Inbound Calls\",\"children\":[{\"type\":\"condition\",\"field\":\"source\",\"operator\":\"contains\",\"value\":\"call\"},{\"type\":\"condition\",\"field\":\"utm_source\",\"operator\":\"contains\",\"value\":\"call\"}]},\"output\":\"Inbound Call\"},{\"conditions\":{\"type\":\"group\",\"match\":\"all\",\"name\":\"Internal Landers\",\"children\":[{\"type\":\"condition\",\"field\":\"supplier_type\",\"operator\":\"equals\",\"value\":\"Internal\"},{\"type\":\"condition\",\"field\":\"optin_url\",\"operator\":\"not_contains\",\"value\":\"/s/\"}]},\"output\":\"Landing Page\"},{\"conditions\":{\"type\":\"group\",\"match\":\"all\",\"name\":\"Leadshook Quiz\",\"children\":[{\"type\":\"condition\",\"field\":\"supplier_type\",\"operator\":\"equals\",\"value\":\"Internal\"},{\"type\":\"condition\",\"field\":\"optin_url\",\"operator\":\"contains\",\"value\":\"/s/\"}]},\"output\":\"Quiz\"},{\"conditions\":{\"type\":\"group\",\"match\":\"all\",\"name\":\"Partner Data - DQ\",\"children\":[{\"type\":\"condition\",\"field\":\"supplier_type\",\"operator\":\"equals\",\"value\":\"External\"},{\"type\":\"condition\",\"field\":\"lead_status\",\"operator\":\"equals\",\"value\":\"Disqualified\"}]},\"output\":\"Partner Data\"},{\"conditions\":{\"type\":\"group\",\"match\":\"all\",\"name\":\"Partner Data - Unsold\",\"children\":[{\"type\":\"condition\",\"field\":\"supplier_type\",\"operator\":\"equals\",\"value\":\"External\"},{\"type\":\"condition\",\"field\":\"lead_status\",\"operator\":\"equals\",\"value\":\"Unsold\"}]},\"output\":\"Partner Data\"},{\"conditions\":{\"type\":\"group\",\"match\":\"all\",\"name\":\"Affiliate\",\"children\":[{\"type\":\"condition\",\"field\":\"supplier_type\",\"operator\":\"equals\",\"value\":\"External\"},{\"type\":\"condition\",\"field\":\"lead_status\",\"operator\":\"equals\",\"value\":\"Sold\"}]},\"output\":\"Affiliate\"},{\"conditions\":{\"type\":\"group\",\"match\":\"any\",\"name\":\"Advertorial\",\"children\":[{\"type\":\"condition\",\"field\":\"utm_source\",\"operator\":\"contains\",\"value\":\"taboola\"},{\"type\":\"condition\",\"field\":\"Supplier Source\",\"operator\":\"contains\",\"value\":\"taboola\"}]},\"output\":\"Advertorial\"},{\"conditions\":{\"type\":\"group\",\"match\":\"any\",\"name\":\"Lead Form\",\"children\":[{\"type\":\"condition\",\"field\":\"utm_campaign\",\"operator\":\"contains\",\"value\":\"form\"},{\"type\":\"condition\",\"field\":\"Supplier Source\",\"operator\":\"contains\",\"value\":\"form\"}]},\"output\":\"Lead Form\"},{\"conditions\":{\"type\":\"group\",\"match\":\"any\",\"name\":\"Email\",\"children\":[{\"type\":\"condition\",\"field\":\"source\",\"operator\":\"contains\",\"value\":\"email\"},{\"type\":\"condition\",\"field\":\"utm_source\",\"operator\":\"contains\",\"value\":\"email\"}]},\"output\":\"Email\"},{\"conditions\":{\"type\":\"group\",\"match\":\"all\",\"name\":\"ChatBot\",\"children\":[{\"type\":\"condition\",\"field\":\"source\",\"operator\":\"contains\",\"value\":\"chat\"}]},\"output\":\"ChatBot\"}],\"fallback\":\"{{supplier_type}}\"}",
    "sort_order": 10,
    "enabled": true
  }
];
